<?php  //[STAMP] f93f1cc3843901744f32012cc1599b49
namespace DmitriiKoziuk\yii2UrlIndex\tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
