<?php
return [
    'url1' => [
        'id' => 1,
        'url' => '/some-url.html',
        'redirect_to_url' => NULL,
        'module_name' => 'module',
        'controller_name' => 'controller',
        'action_name' => 'action',
        'entity_id' => '1',
        'created_at' => '1392559490',
        'updated_at' => '1392559490',
    ],
    'url2' => [
        'id' => 2,
        'url' => '/some-url-2.html',
        'redirect_to_url' => NULL,
        'module_name' => 'module',
        'controller_name' => 'controller',
        'action_name' => 'action',
        'entity_id' => '2',
        'created_at' => '1392569490',
        'updated_at' => '1392569490',
    ],
    'url3' => [
        'id' => 3,
        'url' => '/some-url-3.html',
        'redirect_to_url' => 1,
        'module_name' => 'dk-url-index',
        'controller_name' => 'url',
        'action_name' => 'redirect',
        'entity_id' => '302',
        'created_at' => '1392569490',
        'updated_at' => '1392569490',
    ],
    'url4' => [
        'id' => 4,
        'url' => '/some-url.html?params',
        'redirect_to_url' => NULL,
        'module_name' => 'module',
        'controller_name' => 'controller',
        'action_name' => 'action',
        'entity_id' => '4',
        'created_at' => '1392559490',
        'updated_at' => '1392559490',
    ],
    'url5' => [
        'id' => 5,
        'url' => '/some-url.html?params=value',
        'redirect_to_url' => NULL,
        'module_name' => 'module',
        'controller_name' => 'controller',
        'action_name' => 'action',
        'entity_id' => '5',
        'created_at' => '1392559490',
        'updated_at' => '1392559490',
    ],
    'url6' => [
        'id' => 6,
        'url' => '/test',
        'redirect_to_url' => NULL,
        'module_name' => 'dk-url-index',
        'controller_name' => 'url',
        'action_name' => 'test',
        'entity_id' => '1',
        'created_at' => '1392559490',
        'updated_at' => '1392559490',
    ],
];