<?php
return [
    'url1' => [
        'id' => 1,
        'url' => '/some-url.html',
        'redirect_to_url' => NULL,
        'module_name' => 'module',
        'controller_name' => 'controller',
        'action_name' => 'action',
        'entity_id' => '1',
        'created_at' => '1392559490',
        'updated_at' => '1392559490',
    ],
    'url2' => [
        'id' => 2,
        'url' => '/some-url-2.html',
        'redirect_to_url' => NULL,
        'module_name' => 'module',
        'controller_name' => 'controller',
        'action_name' => 'action',
        'entity_id' => '2',
        'created_at' => '1392569490',
        'updated_at' => '1392569490',
    ],
    'url3' => [
        'id' => 3,
        'url' => '/some-url-3.html',
        'redirect_to_url' => '/some-other-url.html',
        'module_name' => 'module',
        'controller_name' => 'controller',
        'action_name' => 'action',
        'entity_id' => '2',
        'created_at' => '1392569490',
        'updated_at' => '1392569490',
    ],
];